### ISSUE TITLE
Fails to parse bool field

### ISSUE THREAD

**Issue by detj** [QuentinJanuel/AccessDB-parser#7]
Getting this error when trying to parse a large `.accdb` file. Going by the error, it seems it is not able to parse bool field.

```
throw new Error("Failed to parse bool field, Column not found in nullTable column: " + columnName + ", column id: " + column.columnID + ", nullTable: " + nullTable);
                ^

Error: Failed to parse bool field, Column not found in nullTable column: INGESTED, column id: 42, nullTable:
    at AccessTable.parseFixedLengthData (/private/tmp/parse/node_modules/accessdb-parser/lib/index.js:270:23)
    at AccessTable.parseRow (/private/tmp/parse/node_modules/accessdb-parser/lib/index.js:425:18)
    at AccessTable.parse (/private/tmp/parse/node_modules/accessdb-parser/lib/index.js:465:26)
    at AccessParser.parseTableUnformatted (/private/tmp/parse/node_modules/accessdb-parser/lib/index.js:134:28)
    at AccessParser.parseTable (/private/tmp/parse/node_modules/accessdb-parser/lib/index.js:137:26)
    at /private/tmp/parse/index.js:12:19
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/private/tmp/parse/index.js:10:8)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
```

**Comment by QuentinJanuel** [comment]
Hi,

I'm sorry, this project is just a TypeScript rewrite of a Python version, so I have no clue how it works under the hood.
Chances are this bug is also in the Python version, so I'd recommend posting the issue on their repo:
https://github.com/claroty/access_parser

Best of luck

**Comment by detj** [comment]
thanks for the reply. I used a different mechanism to get my jod done. feel free to close this issue.

**Comment by lmdc45** [comment]
it seems it has been fixed in the code however npm version is still with the bug. Would it be possible to publish v2 on npm?
